### PR TITLE
Sending multiple transfers at once with Wallet V3

### PR DESCRIPTION
**Pull request by ton-solutions**

### CODE REVIEW

**Comment by ex3ndr** [comment]
I am not sure if ` if (this.order instanceof Array) {` is a correct check for an array. Also what about other wallet contracts?

**Comment by ton-solutions** [comment]
@ex3ndr I have changed `instanceof Array` to `Array.isArray`.
Regarding other wallet contracts: I am not sure, if they support multiple orders, since they are presented compiled (boc) in this repository.

**Comment by ex3ndr** [comment]
You can have an idea of classic wallet contracts by looking here:

https://github.com/ton-foundation/ton/blob/master/crypto/smartcont/simple-wallet-code.fc
https://github.com/ton-foundation/ton/blob/master/crypto/smartcont/simple-wallet-ext-code.fc
https://github.com/ton-foundation/ton/blob/master/crypto/smartcont/wallet-code.fc
https://github.com/ton-foundation/ton/blob/master/crypto/smartcont/wallet3-code.fc

They all are +- the same.

Also, this is a critical infrastructure library, tests should be implemented. I know it is not trivial to test with our flacky testnet, but I have to be done.

**Comment by ex3ndr** [comment]
Fixed in latest versions

**Pull request closed without merging**
