### PR TITLE
Explicit parse.ts types

### PR DESCRIPTION
**Pull request by shaharyakir**
# Context
Currently, there are a few inline types that make using typescript casting hard and verbose. For example,
```
type RawTransactionDescription =
    | {
        type: 'generic',
        ...
        computePhase: RawComputePhase,
        ...
    }
    | {
        type: 'storage',
        ....
    }
    | {
        type: 'tick-tock',
        ...
    };
 ```

When working with typescript, in order to be able to reach the `computePhase` property, we have to cast to the full type description.

# This PR

This change adds explicit types for each such that:
```
export type RawTransactionDescription =
  | GenericTransactionDescription
  | StorageTransactionDescription
  | TickTockTransactionDescription

...
```

Which will make casting in typescript much easier.

### CODE REVIEW

**Comment by shaharyakir** [comment]
Actually, I wonder if we're willing to make a breaking change and replace `Raw...` types with union types directly.
Otherwise, it's when a function returns `RawTransactionDescription` it's not easy to know whether it in fact translates to multiple types.

**Review by dvlkv — APPROVED** [review]
LGTM, @ex3ndr that do you think?

**Comment by dvlkv** [comment]
@shaharyakir can you please remove changes to `package.json`? It will go to the next release

**Comment by shaharyakir** [comment]
@dvlkv done

**Comment by dvlkv** [comment]
And CHANGELOG also as well

**Pull request merged**
